/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanSlider: typeof import('vant/es')['Slider']
    VanSpace: typeof import('vant/es')['Space']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanCol: typeof import('vant/es')['Col']
  const VanDropdownItem: typeof import('vant/es')['DropdownItem']
  const VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
  const VanField: typeof import('vant/es')['Field']
  const VanForm: typeof import('vant/es')['Form']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanImage: typeof import('vant/es')['Image']
  const VanList: typeof import('vant/es')['List']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanNoticeBar: typeof import('vant/es')['NoticeBar']
  const VanPicker: typeof import('vant/es')['Picker']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanRow: typeof import('vant/es')['Row']
  const VanSlider: typeof import('vant/es')['Slider']
  const VanSpace: typeof import('vant/es')['Space']
  const VanSwitch: typeof import('vant/es')['Switch']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanTabs: typeof import('vant/es')['Tabs']
  const VanUploader: typeof import('vant/es')['Uploader']
}